version: '3'
services:
  tad:
    image: 'mongo:latest'
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="mongodb"
      - MONGODB_PASS="mongodb"
    volumes:
      - './data/db:/data/db'
    ports:
      - '27017:27017'


      #caminho relativo para usar no windows /tmp/database:/var/lib/mongodb/data -e
      #caminho relativo para usar no linux ./data/db:/data/db
