version: "3"
services:
  tad:
    image: mongo:latest
    container_name: "mongodb"
    environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        - MONGODB_USER="" 
        - MONGODB_PASS=""
    volumes:
        - ./data/db:/data/db
    ports:
        - 27017:27017
    