version: "3"
services:
  tad:
    image: postgres:latest
    container_name: "postgres"
    environment:
      - POSTGRES_DB=tadpgweb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
#https://jtemporal.com/brincando-com-postgresql/

#caminha relativo para usar no windows /tmp/database:/var/lib/postgresql/data -e
#caminho relativo para usar no linux ./data/postgres:/var/lib/postgresql/data
